---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: jenkins-ver2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata: 
      labels:
        app: jenkins-ver2
        version: 1.625.1
    spec:
      containers:
        - image: jenkins:2.60.3
          name: jenkins-ver2 
          ports:
            - protocol: TCP
              containerPort: 8080

            
