apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-rs
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app:nginx  
  template:
    spec:
      initContainers:
        - image: alpine
          name: ping
          command: ["ping","-c","4","google.com"]
      containers:
        - image: nginx
          name: nginx-cont
          ports:
            - containerPort: 80
              protocol: TCP
